arb-dir: lib/l10n
template-arb-file: app_ko.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n
output-class: AppLocalizations
synthetic-package: false
untranslated-messages-file: lib/l10n/not_implements.txt