arb-dir: assets/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/l10n
output-class: AppLocalizations
use-deferred-loading: false
synthetic-package: false
untranslated-messages-file: lib/core/l10n/generated/not_implements.txt