name: COUPLE_BOOK
description: "Couple Book"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localize
  flutter_localizations:
    sdk: flutter
  intl: any

  # Ui
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

  # Util
  flutter_local_notifications: ^17.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.2.4
  path_provider: ^2.1.3
  cuid2: ^3.1.0
  logger: ^2.2.0
  device_info_plus: ^10.1.0
  flutter_timezone: ^1.0.8
  url_launcher: ^6.2.6
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  analyzer: ^6.4.1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    rive: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/bgImgs/
    - assets/colors/
    - assets/contents/
  fonts:
    - family: Iseoyunchae
      fonts:
        - asset: fonts/이서윤체.ttf

    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansKR-Black.ttf
          weight: 900

